all: true
with-expecter: true
filename: "mock_{{.InterfaceName | lower }}.gen_test.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/microserv-io/oauth2-token-vault/internal/app/oauthapp:
    config:
      recursive: true
  github.com/microserv-io/oauth2-token-vault/internal/app/provider:
    config:
      recursive: true
  github.com/microserv-io/oauth2-token-vault/internal/infrastructure/grpc:
    config:
      recursive: true
