all: true
with-expecter: true
filename: "mock_{{.InterfaceName | lower }}.gen_test.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/microserv-io/oauth-credentials-server/internal/app/oauthapp:
    config:
      recursive: true
